### PR TITLE
translation file generated for language_code:gu and added translated entries

### PR DESCRIPTION
**Pull request by dhruvilxcode**
`translation/gu.csv` added. 
Translation strings added.

### CODE REVIEW

**Comment by mohsinalimat** [comment]
Use file name like as gj same as four wheeler number.

**Comment by dhruvilxcode** [comment]
@mohsinalimat it's not user-generated, this is [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) code. the script itself generates a file name. 

if something is missing, let me know.

**Comment by 18alantom** [comment]
@dhruvilxcode looks good.

Several missing translations though, any reason for these?

Also you'll need to add `Gujrati: 'gu'` in `language.ts`, after this: https://github.com/frappe/books/blob/984a5013852ef745a7d622c8d76ff7eaf3f7f7a3/src/utils/language.ts#L17

**Comment by dhruvilxcode** [comment]
@18alantom added in `language.ts`.

by missing I guess you're referring to not translated? Some translations I found were a bit weird in the translated language, so I kept English there.

**Comment by dhruvilxcode** [comment]
Thanks, @18alantom for merging PR. ✌️

**Comment by ankush** [comment]
_Mast_. Did you use any machine translation tool or manually translated it? @dhruvilxcode

**Pull request merged**
