### PR TITLE
docs: update README.md with flatpak installation instructions

### PR DESCRIPTION
**Pull request by akshayitzme**

### CODE REVIEW

**Comment by kskarthik** [comment]
@akshayitzme could you help with attaining the verification badge https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by akshayitzme** [comment]
> @akshayitzme could you help with attaining the verification badge https://docs.flathub.org/docs/for-app-authors/verification/

Sure, I'd love to help. I've read the doc you shared, They quoted
> First step is to gain ownership over your app

Currently, you hold the ownership I believe?. Should I initiate the steps to transfer the ownership to mine if you are fine with it ?.

**Comment by kskarthik** [comment]
> Currently, you hold the ownership I believe?. Should I initiate the steps to transfer the ownership to mine if you are fine with it ?

Ok, Sure

I guess the process is https://docs.flathub.org/docs/for-app-authors/submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do

**Comment by kskarthik** [comment]
@akshayitzme you can follow https://github.com/flathub/flathub/issues/5812

**Pull request merged**
