### PR TITLE
Update README.md with flatpak installation instructions

### PR DESCRIPTION
**Pull request by kskarthik**

### CODE REVIEW

**Comment by akshayitzme** [comment]
@kskarthik , I tried the flatpack version. But it shown an unresponsive white screen. Does this issue occurs to you too ?.

So I'm reverting this PR till this issue is fixed.

**Comment by kskarthik** [comment]
> @kskarthik , I tried the flatpack version. But it shown an unresponsive white screen. Does this issue occurs to you too ?.
> 
> So I'm reverting this PR till this issue is fixed.

are you sure? just checked myself & it works as expected 

image

**Comment by kskarthik** [comment]
@akshayitzme found the issue & patched in the new release https://github.com/flathub/io.frappe.books/pull/2

Will be available soon on flathub!

Thank you for reporting

**Comment by akshayitzme** [comment]
> @akshayitzme found the issue & patched in the new release [flathub/io.frappe.books#2](https://github.com/flathub/io.frappe.books/pull/2)
> 
> Will be available soon on flathub!
> 
> Thank you for reporting

Great work 👍🏻. I'll test the new version after it releases, then update the docs

**Comment by kskarthik** [comment]
@akshayitzme the new version is out, do try it & let me know if you find any issues

**Comment by akshayitzme** [comment]
> @akshayitzme the new version is out, do try it & let me know if you find any issues

Tried new version, worked well without any issues 👍🏻 . I've updated the docs in  #1007

**Pull request merged**
