### PR TITLE
Add ability to view and export GSTR II

### PR DESCRIPTION
**Pull request by piyushsinghania**
cc: @ankitsinghaniyaz @18alantom

### CODE REVIEW

**Comment by 18alantom** [comment]
@piyushsinghania can you allow [edits](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on this PR. I can't push fixes or resolve rebase conflicts.

**Review by 18alantom — COMMENTED** [review]
Everything looks fine. Just a query:
- Why doesn't GSTR-1 have `csv` export?
- Why doesn't GSTR-2 have `json` export?

(cc @ankitsinghaniyaz)

**Comment by piyushsinghania** [comment]
I guess this is already enabled? @18alantom can you confirm, or do I need to do something else?
image

**Comment by piyushsinghania** [comment]
Regarding this - 

> Everything looks fine. Just a query:
> 
> * Why doesn't GSTR-1 have `csv` export?
> * Why doesn't GSTR-2 have `json` export?
> 
> (cc @ankitsinghaniyaz)


It's actually inspired from EN, 
one can directly upload GSTR-1 data as json to GST-portal for filling purposes.
Whereas GSTR-2 is now generated by the GSTR-1 reports filled/submitted by the suppliers and can be availed from GST-portal itself.
Yes, we can add **export as csv** to GSTR-1 also (It's there in EN). And it can be then raised in a separate PR.

@18alantom 

image

**Comment by 18alantom** [comment]
> I guess this is already enabled? @18alantom can you confirm, or do I need to do something else? 

I'm unable to push to this PR for some reason 🤨

**Comment by 18alantom** [comment]
> Yes, we can add **export as csv** to GSTR-1 also (It's there in EN). And it can be then raised in a separate PR.

We'll add it in later then, CSV and JSON for both.

**Comment by 18alantom** [comment]
Creating a merge commit instead of rebasing cause of rebase conflicts. exports will be pushed through later PRs

**Pull request merged**
