### PR TITLE
Added Hindi language (hi) code and Hindi translation file hi.csv

### PR DESCRIPTION
**Pull request by bnsinghgit**
Added Hindi language (hi) code in file [ .../src/utils/language.ts ] after entry for Gujarati language, and updated Hindi translations in file hi.csv

### CODE REVIEW

**Comment by bnsinghgit** [comment]
I installed the Books current release( 0.22 version). But there is no entry appearing for Hindi language selection in the DB language selection list.

**Comment by akshayitzme** [comment]
> I installed the Books current release( 0.22 version). But there is no entry appearing for Hindi language selection in the DB language selection list.

v0.22 is released before merging this pull request thus this translation is not included in the 0.22 version. It will be available from the next release.

**Comment by bnsinghgit** [comment]
Thanks for confirmation



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by akshayitzme** [comment]
> > I installed the Books current release( 0.22 version). But there is no entry appearing for Hindi language selection in the DB language selection list.
> 
> v0.22 is released before merging this pull request thus this translation is not included in the 0.22 version. It will be available from the next release.

Hi @bnsinghgit , 

FYI, Hindi Language is usable from the [v0.23.0 release](https://github.com/frappe/books/releases/tag/v0.23.0)

**Pull request merged**
